server:
  port: 8082
spring:
  application:
    name: account-service
  profiles: test
  jpa:
    show-sql: false
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false